name: Compilation

on: push

jobs:

  compile:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Size
        run: du -skh --exclude=".git"

      - name: make fclean
        run: make fclean

      - name: make clean
        run: make clean

      - name: make
        run: make