name: pushin_p

on: push

jobs:

  warnings:
    needs: compile

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4.9.4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master

  pushin_p:
    needs: compile

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: pushing
        uses: pixta-dev/repository-mirroring-action@v1.1.0
        with:
          target_repo_url:
            git@github.com:ErwanC7/infin_add2.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}