name: repository_mirroring.yml
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "c\'est pas clair"
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:ErwanC7/infin_add2.git
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}